name: domi
description: Delivery services.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3  #android
# version: 1.0.2+5  #ios

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  google_fonts: ^2.0.0
  intl: ^0.17.0
  image_picker: ^0.7.4
  flutter_secure_storage: ^4.2.0
  json_annotation: ^4.0.1
  http: ^0.13.3
  flutter_riverpod: ^0.14.0+3
  google_maps_flutter: ^2.0.6
  timeago: ^3.0.2
  flutter_rating_bar: ^4.0.0
  uuid: ^3.0.4
  flutter_inappwebview: ^5.3.2
  location: ^4.3.0
  web_socket_channel: ^2.1.0
  decimal: ^1.1.0
  url_launcher: ^6.0.4
  email_validator: ^2.0.1
  share_plus: ^2.1.4
  onesignal_flutter: ^3.0.0
  location_permissions: ^4.0.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.2
  json_serializable: ^4.1.1
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4


flutter_native_splash:

  color: "#FFE700"
  image: assets/icons/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/geo/
    - assets/html/
    - assets/cc/